### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by McPringle**
This change is [Reviewable](https://reviewable.io/reviews/zdila/gpx-animator/30)

### CODE REVIEW

**Comment by zdila** [comment]
Will it work also with older JRE, like Java 8? Because it is a default java version offered by Oracle for my Debian linux.

**Comment by McPringle** [comment]
If you have Java 8 installed, you should update immediately. Java 8 public support ended on September 25th 2018 and if you want any further (security) updates, you have to pay Oracle for a license (then you can download the updates after logging in on the Oracle website).

Debian supports OpenJDK which has a six month release cycle with six month of support for (security) updates. Debian creates backports of the actual supported OpenJDK versions for Debian Stretch, which is as of today OpenJDK 11. All versions before 11 are out of public support since September 25th, 2018.

On my Chromebook I run a Linux emulation which is based on Debian 9 and Java 11 works fine. If you are developing software using Java, I highly recommend using [SDKMan](https://sdkman.io/). It supports switching between different Java version on the fly.

**Comment by zdila** [comment]
Thanks for your answer. I understand what you say, but general user will just download default java offered and for me it was surprisingly that old Java 8. Is it difficult to support it?

**Comment by McPringle** [comment]
I made no Java code changes. Changing the corresponding properties in the build file will generate Java 8 compatible class files. I did the change a few minutes ago.

But having Java 8 installed is a security risk!

**Pull request merged**
