### PR TITLE
proposal for #111

### PR DESCRIPTION
**Pull request by heroichornet**
a proposal for the logo, Maybe it would be better to have an icon without letters, what do you guys think?

### CODE REVIEW

**Comment by McPringle** [comment]
Nice work -- but I would expect this icon as a file icon for *.gpx files, not for the program itself. :-)

**Comment by heroichornet** [comment]
The film stripes symbolize the animation part and the gpx the file format. As mentioned in the issue. One suggestion would be the ;) winking smiley inside the logo. Or maybe something not so relevant like an animal or something abstract

**Comment by McPringle** [comment]
I would start with the high-resolution icon. I think of a film strip, too but inside the film strip a map with a red line and a dot, like a film strip was cut out of a GPX Animator movie. What do you think?

**Comment by McPringle** [comment]
But keep this icon with the red background and white "gpx". I could use this to register a file icon for the "*.ga.xml" extension (saved GPX Animator movie configuration).

**Comment by heroichornet** [comment]
Ok we can try that, it just isnt allowed to be too complex ive realized, otherwise it will not be recognizable at low resolutions, like maybe we we could look at logo like the gradle logo the elephant. For example we just take a cheetah or a panther which is a very "animated"anmial, what do think?

**Comment by heroichornet** [comment]
@McPringle  what about this proposal? 

ico

**Comment by McPringle** [comment]
The issue #111 was done at the July Hackergarten in Lucerne.

**Pull request closed without merging**
